/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TownsLazyRouteImport = createFileRoute('/towns')()
const RegionsLazyRouteImport = createFileRoute('/regions')()
const LocationsLazyRouteImport = createFileRoute('/locations')()
const ItemsLazyRouteImport = createFileRoute('/items')()
const IndexLazyRouteImport = createFileRoute('/')()

const TownsLazyRoute = TownsLazyRouteImport.update({
  id: '/towns',
  path: '/towns',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/towns.lazy').then((d) => d.Route))
const RegionsLazyRoute = RegionsLazyRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/regions.lazy').then((d) => d.Route))
const LocationsLazyRoute = LocationsLazyRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/locations.lazy').then((d) => d.Route))
const ItemsLazyRoute = ItemsLazyRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/items.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/items': typeof ItemsLazyRoute
  '/locations': typeof LocationsLazyRoute
  '/regions': typeof RegionsLazyRoute
  '/towns': typeof TownsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/items': typeof ItemsLazyRoute
  '/locations': typeof LocationsLazyRoute
  '/regions': typeof RegionsLazyRoute
  '/towns': typeof TownsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/items': typeof ItemsLazyRoute
  '/locations': typeof LocationsLazyRoute
  '/regions': typeof RegionsLazyRoute
  '/towns': typeof TownsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items' | '/locations' | '/regions' | '/towns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items' | '/locations' | '/regions' | '/towns'
  id: '__root__' | '/' | '/items' | '/locations' | '/regions' | '/towns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ItemsLazyRoute: typeof ItemsLazyRoute
  LocationsLazyRoute: typeof LocationsLazyRoute
  RegionsLazyRoute: typeof RegionsLazyRoute
  TownsLazyRoute: typeof TownsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/towns': {
      id: '/towns'
      path: '/towns'
      fullPath: '/towns'
      preLoaderRoute: typeof TownsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ItemsLazyRoute: ItemsLazyRoute,
  LocationsLazyRoute: LocationsLazyRoute,
  RegionsLazyRoute: RegionsLazyRoute,
  TownsLazyRoute: TownsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
